// This file is generated by web/scripts/generate-registry.mjs.
// Do not edit it by hand.

import type { Tool } from "./registry";

export const tools: Tool[] = [
  {
    "id": "aws",
    "name": "aws",
    "display_name": "AWS CLI",
    "description": "Official CLI for Amazon Web Services — manage AWS resources",
    "command": "aws",
    "homepage": "https://aws.amazon.com/cli/",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "cloud",
      "aws",
      "infrastructure",
      "devops"
    ],
    "examples": [
      "aws s3 ls",
      "aws ec2 describe-instances --output json",
      "aws sts get-caller-identity"
    ]
  },
  {
    "id": "docker",
    "name": "docker",
    "display_name": "Docker CLI",
    "description": "Build, run, and manage containers and images",
    "command": "docker",
    "homepage": "https://www.docker.com",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "containers",
      "devops",
      "build",
      "infrastructure"
    ],
    "examples": [
      "docker ps",
      "docker build -t myapp .",
      "docker compose up -d",
      "docker images --format json"
    ]
  },
  {
    "id": "firebase",
    "name": "firebase",
    "display_name": "Firebase CLI",
    "description": "Manage Firebase projects — hosting, functions, Firestore, and auth",
    "command": "firebase",
    "homepage": "https://firebase.google.com/docs/cli",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "npm",
    "tags": [
      "google",
      "cloud",
      "backend",
      "hosting",
      "serverless"
    ],
    "examples": [
      "firebase projects:list",
      "firebase deploy --only hosting",
      "firebase emulators:start"
    ]
  },
  {
    "id": "fly",
    "name": "fly",
    "display_name": "Fly.io CLI",
    "description": "Deploy and manage apps on Fly.io's global platform",
    "command": "fly",
    "homepage": "https://fly.io",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "cloud",
      "deploy",
      "hosting",
      "containers"
    ],
    "examples": [
      "fly apps list",
      "fly deploy",
      "fly status --json"
    ]
  },
  {
    "id": "github",
    "name": "github",
    "display_name": "GitHub CLI",
    "description": "Official CLI for GitHub — manage repos, PRs, issues, and more",
    "command": "gh",
    "homepage": "https://cli.github.com",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "git",
      "github",
      "scm",
      "vcs"
    ],
    "examples": [
      "gh repo list",
      "gh issue list",
      "gh pr create --title \"fix: typo\" --body \"Fixed a typo\""
    ]
  },
  {
    "id": "kubectl",
    "name": "kubectl",
    "display_name": "kubectl",
    "description": "Kubernetes CLI — manage clusters, deployments, and services",
    "command": "kubectl",
    "homepage": "https://kubernetes.io/docs/reference/kubectl/",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "kubernetes",
      "containers",
      "orchestration",
      "devops"
    ],
    "examples": [
      "kubectl get pods -A",
      "kubectl apply -f deployment.yaml",
      "kubectl logs -f deployment/myapp",
      "kubectl get nodes -o json"
    ]
  },
  {
    "id": "netlify",
    "name": "netlify",
    "display_name": "Netlify CLI",
    "description": "Deploy sites and manage Netlify services from the command line",
    "command": "netlify",
    "homepage": "https://www.netlify.com/products/cli/",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "npm",
    "tags": [
      "deploy",
      "hosting",
      "jamstack",
      "serverless"
    ],
    "examples": [
      "netlify deploy --prod",
      "netlify sites:list --json",
      "netlify dev"
    ]
  },
  {
    "id": "railway",
    "name": "railway",
    "display_name": "Railway CLI",
    "description": "Deploy and manage projects on Railway — databases, services, and more",
    "command": "railway",
    "homepage": "https://railway.app",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "cloud",
      "deploy",
      "hosting",
      "database"
    ],
    "examples": [
      "railway status",
      "railway up",
      "railway logs"
    ]
  },
  {
    "id": "stripe",
    "name": "stripe",
    "display_name": "Stripe CLI",
    "description": "Official CLI for Stripe — test webhooks, manage resources, and trigger events",
    "command": "stripe",
    "homepage": "https://stripe.com/docs/stripe-cli",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "payments",
      "stripe",
      "fintech",
      "webhooks"
    ],
    "examples": [
      "stripe listen --forward-to localhost:3000/webhook",
      "stripe trigger payment_intent.succeeded",
      "stripe resources list"
    ]
  },
  {
    "id": "supabase",
    "name": "supabase",
    "display_name": "Supabase CLI",
    "description": "Manage Supabase projects — database, auth, storage, and edge functions",
    "command": "supabase",
    "homepage": "https://supabase.com/docs/guides/cli",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "database",
      "backend",
      "auth",
      "serverless"
    ],
    "examples": [
      "supabase projects list",
      "supabase db push",
      "supabase functions deploy my-function"
    ]
  },
  {
    "id": "terraform",
    "name": "terraform",
    "display_name": "Terraform CLI",
    "description": "Infrastructure as Code — provision and manage cloud resources declaratively",
    "command": "terraform",
    "homepage": "https://www.terraform.io",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "infrastructure",
      "iac",
      "cloud",
      "devops"
    ],
    "examples": [
      "terraform init",
      "terraform plan -out=plan.tfplan",
      "terraform apply plan.tfplan",
      "terraform state list"
    ]
  },
  {
    "id": "turso",
    "name": "turso",
    "display_name": "Turso CLI",
    "description": "CLI for Turso — the edge SQLite database built on libSQL",
    "command": "turso",
    "homepage": "https://turso.tech",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "tags": [
      "database",
      "sqlite",
      "edge"
    ],
    "examples": [
      "turso db list",
      "turso db create my-db",
      "turso db shell my-db"
    ]
  },
  {
    "id": "vercel",
    "name": "vercel",
    "display_name": "Vercel CLI",
    "description": "Deploy and manage Vercel projects from the command line",
    "command": "vercel",
    "homepage": "https://vercel.com/docs/cli",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "npm",
    "tags": [
      "deploy",
      "hosting",
      "serverless",
      "frontend"
    ],
    "examples": [
      "vercel deploy",
      "vercel env ls",
      "vercel domains ls"
    ]
  },
  {
    "id": "wrangler",
    "name": "wrangler",
    "display_name": "Cloudflare Wrangler",
    "description": "CLI for Cloudflare Workers — develop, test, and deploy serverless functions",
    "command": "wrangler",
    "homepage": "https://developers.cloudflare.com/workers/wrangler",
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": false,
    "install_default": "npm",
    "tags": [
      "cloudflare",
      "deploy",
      "serverless",
      "workers",
      "edge"
    ],
    "examples": [
      "wrangler init my-project",
      "wrangler deploy",
      "wrangler dev"
    ]
  }
];

export const allTags: string[] = [
  "auth",
  "aws",
  "backend",
  "build",
  "cloud",
  "cloudflare",
  "containers",
  "database",
  "deploy",
  "devops",
  "edge",
  "fintech",
  "frontend",
  "git",
  "github",
  "google",
  "hosting",
  "iac",
  "infrastructure",
  "jamstack",
  "kubernetes",
  "orchestration",
  "payments",
  "scm",
  "serverless",
  "sqlite",
  "stripe",
  "vcs",
  "webhooks",
  "workers"
];
