// This file is generated by web/scripts/generate-registry.mjs.
// Do not edit it by hand.

import type { Tool } from "./registry";

export const tools: Tool[] = [
  {
    "id": "aws",
    "name": "aws",
    "display_name": "AWS CLI",
    "description": "Official CLI for Amazon Web Services — manage AWS resources",
    "command": "aws",
    "homepage": "https://aws.amazon.com/cli/",
    "aliases": [
      "awscli"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "recommended_version": ">=2.15.0",
    "install_default": "brew",
    "install_default_package": "awscli",
    "install_alternatives": [
      {
        "type": "pipx",
        "package": "awscli"
      },
      {
        "type": "binary",
        "url": "https://aws.amazon.com/cli/",
        "note": "Download official installer from AWS"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Run `aws configure` or set AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY",
      "Use `aws sso login` for SSO-based access"
    ],
    "tags": [
      "cloud",
      "aws",
      "infrastructure",
      "devops"
    ],
    "examples": [
      "aws s3 ls",
      "aws ec2 describe-instances --output json",
      "aws sts get-caller-identity"
    ]
  },
  {
    "id": "docker",
    "name": "docker",
    "display_name": "Docker CLI",
    "description": "Build, run, and manage containers and images",
    "command": "docker",
    "homepage": "https://www.docker.com",
    "aliases": [],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "install_default_package": "docker",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://docs.docker.com/get-docker/",
        "note": "Install Docker Desktop or Docker Engine"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Run `docker login` to authenticate with Docker Hub",
      "Docker daemon must be running"
    ],
    "tags": [
      "containers",
      "devops",
      "build",
      "infrastructure"
    ],
    "examples": [
      "docker ps",
      "docker build -t myapp .",
      "docker compose up -d",
      "docker images --format json"
    ]
  },
  {
    "id": "feishu",
    "name": "feishu",
    "display_name": "Lark / Feishu CLI",
    "description": "Official CLI for Lark / Feishu Open Platform — messaging, docs, sheets, calendar, mail, and more",
    "command": "lark-cli",
    "homepage": "https://github.com/larksuite/cli",
    "aliases": [
      "lark",
      "larksuite",
      "lark-cli",
      "feishu-cli"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "npm",
    "install_default_package": "@larksuite/cli",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://github.com/larksuite/cli",
        "note": "Build from source with Go and Python"
      }
    ],
    "prerequisites": [
      "node"
    ],
    "auth_notes": [
      "Run `lark-cli config init --new` to create app credentials",
      "Run `lark-cli auth login --recommend` to authorize user scopes",
      "Use `lark-cli auth status` to verify the current login state"
    ],
    "tags": [
      "feishu",
      "lark",
      "collaboration",
      "productivity",
      "messaging",
      "docs"
    ],
    "examples": [
      "lark-cli auth status",
      "lark-cli calendar +agenda",
      "lark-cli im +messages-send --chat-id oc_xxx --text \"Hello\""
    ]
  },
  {
    "id": "firebase",
    "name": "firebase",
    "display_name": "Firebase CLI",
    "description": "Manage Firebase projects — hosting, functions, Firestore, and auth",
    "command": "firebase",
    "homepage": "https://firebase.google.com/docs/cli",
    "aliases": [],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "npm",
    "install_default_package": "firebase-tools",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://firebase.google.com/docs/cli#install-cli-mac-linux",
        "note": "Standalone binary for macOS/Linux"
      }
    ],
    "prerequisites": [
      "node"
    ],
    "auth_notes": [
      "Run `firebase login` to authenticate with Google",
      "Use `firebase login:ci` for CI token"
    ],
    "tags": [
      "google",
      "cloud",
      "backend",
      "hosting",
      "serverless"
    ],
    "examples": [
      "firebase projects:list",
      "firebase deploy --only hosting",
      "firebase emulators:start"
    ]
  },
  {
    "id": "fly",
    "name": "fly",
    "display_name": "Fly.io CLI",
    "description": "Deploy and manage apps on Fly.io's global platform",
    "command": "fly",
    "homepage": "https://fly.io",
    "aliases": [
      "flyctl"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "recommended_version": ">=0.3.0",
    "install_default": "brew",
    "install_default_package": "flyctl",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://fly.io/docs/flyctl/install/",
        "note": "Install via official script"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Run `fly auth login` before deploying"
    ],
    "tags": [
      "cloud",
      "deploy",
      "hosting",
      "containers"
    ],
    "examples": [
      "fly apps list",
      "fly deploy",
      "fly status --json"
    ]
  },
  {
    "id": "github",
    "name": "github",
    "display_name": "GitHub CLI",
    "description": "Official CLI for GitHub — manage repos, PRs, issues, and more",
    "command": "gh",
    "homepage": "https://cli.github.com",
    "aliases": [
      "gh"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "recommended_version": ">=2.40.0",
    "install_default": "brew",
    "install_default_package": "gh",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://github.com/cli/cli/releases",
        "note": "Download pre-built binary from GitHub Releases"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Run `gh auth login` before using most commands",
      "Most read operations on public repos do not require auth"
    ],
    "tags": [
      "git",
      "github",
      "scm",
      "vcs"
    ],
    "examples": [
      "gh repo list",
      "gh issue list",
      "gh pr create --title \"fix: typo\" --body \"Fixed a typo\""
    ]
  },
  {
    "id": "google-workspace",
    "name": "google-workspace",
    "display_name": "Google Workspace CLI",
    "description": "CLI for Drive, Gmail, Calendar, Sheets, Docs, Chat, Admin, and more, with structured JSON output",
    "command": "gws",
    "homepage": "https://github.com/googleworkspace/cli",
    "aliases": [
      "gws",
      "googleworkspace",
      "googleworkspace-cli"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "npm",
    "install_default_package": "@googleworkspace/cli",
    "install_alternatives": [
      {
        "type": "brew",
        "package": "googleworkspace-cli"
      },
      {
        "type": "binary",
        "url": "https://github.com/googleworkspace/cli/releases",
        "note": "Download a pre-built binary from GitHub Releases"
      }
    ],
    "prerequisites": [
      "node",
      "google-cloud-project",
      "google-account"
    ],
    "auth_notes": [
      "Run `gws auth setup` for the fastest local setup when `gcloud` is installed",
      "Run `gws auth login` after configuring OAuth credentials",
      "CI and headless setups can use GOOGLE_WORKSPACE_CLI_CREDENTIALS_FILE or GOOGLE_WORKSPACE_CLI_TOKEN"
    ],
    "tags": [
      "google",
      "workspace",
      "gmail",
      "drive",
      "docs",
      "sheets",
      "productivity"
    ],
    "examples": [
      "gws auth setup",
      "gws drive files list --params '{\"pageSize\": 5}'",
      "gws sheets spreadsheets create --json '{\"properties\": {\"title\": \"Q1 Budget\"}}'"
    ]
  },
  {
    "id": "kubectl",
    "name": "kubectl",
    "display_name": "kubectl",
    "description": "Kubernetes CLI — manage clusters, deployments, and services",
    "command": "kubectl",
    "homepage": "https://kubernetes.io/docs/reference/kubectl/",
    "aliases": [
      "k8s"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "recommended_version": ">=1.29.0",
    "install_default": "brew",
    "install_default_package": "kubectl",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://kubernetes.io/docs/tasks/tools/",
        "note": "Download from Kubernetes docs"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Configure kubeconfig (~/.kube/config) or set KUBECONFIG",
      "Use cloud provider CLI to get cluster credentials"
    ],
    "tags": [
      "kubernetes",
      "containers",
      "orchestration",
      "devops"
    ],
    "examples": [
      "kubectl get pods -A",
      "kubectl apply -f deployment.yaml",
      "kubectl logs -f deployment/myapp",
      "kubectl get nodes -o json"
    ]
  },
  {
    "id": "netlify",
    "name": "netlify",
    "display_name": "Netlify CLI",
    "description": "Deploy sites and manage Netlify services from the command line",
    "command": "netlify",
    "homepage": "https://www.netlify.com/products/cli/",
    "aliases": [
      "ntl"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "npm",
    "install_default_package": "netlify-cli",
    "install_alternatives": [
      {
        "type": "brew",
        "package": "netlify-cli"
      }
    ],
    "prerequisites": [
      "node"
    ],
    "auth_notes": [
      "Run `netlify login` to authenticate",
      "Set NETLIFY_AUTH_TOKEN for CI/CD"
    ],
    "tags": [
      "deploy",
      "hosting",
      "jamstack",
      "serverless"
    ],
    "examples": [
      "netlify deploy --prod",
      "netlify sites:list --json",
      "netlify dev"
    ]
  },
  {
    "id": "railway",
    "name": "railway",
    "display_name": "Railway CLI",
    "description": "Deploy and manage projects on Railway — databases, services, and more",
    "command": "railway",
    "homepage": "https://railway.app",
    "aliases": [
      "rw"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "install_default_package": "railway",
    "install_alternatives": [
      {
        "type": "npm",
        "package": "@railway/cli"
      },
      {
        "type": "binary",
        "url": "https://docs.railway.app/guides/cli",
        "note": "Install via official script"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Run `railway login` to authenticate",
      "Set RAILWAY_TOKEN for CI/CD"
    ],
    "tags": [
      "cloud",
      "deploy",
      "hosting",
      "database"
    ],
    "examples": [
      "railway status",
      "railway up",
      "railway logs"
    ]
  },
  {
    "id": "stripe",
    "name": "stripe",
    "display_name": "Stripe CLI",
    "description": "Official CLI for Stripe — test webhooks, manage resources, and trigger events",
    "command": "stripe",
    "homepage": "https://stripe.com/docs/stripe-cli",
    "aliases": [
      "stripe-cli"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "recommended_version": ">=1.19.0",
    "install_default": "brew",
    "install_default_package": "stripe/stripe-cli/stripe",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://github.com/stripe/stripe-cli/releases",
        "note": "Download pre-built binary from GitHub Releases"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Run `stripe login` to authenticate via browser",
      "API keys can be set via STRIPE_API_KEY"
    ],
    "tags": [
      "payments",
      "stripe",
      "fintech",
      "webhooks"
    ],
    "examples": [
      "stripe listen --forward-to localhost:3000/webhook",
      "stripe trigger payment_intent.succeeded",
      "stripe resources list"
    ]
  },
  {
    "id": "supabase",
    "name": "supabase",
    "display_name": "Supabase CLI",
    "description": "Manage Supabase projects — database, auth, storage, and edge functions",
    "command": "supabase",
    "homepage": "https://supabase.com/docs/guides/cli",
    "aliases": [],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "recommended_version": ">=2.0.0",
    "install_default": "brew",
    "install_default_package": "supabase/tap/supabase",
    "install_alternatives": [
      {
        "type": "npm",
        "package": "supabase"
      },
      {
        "type": "binary",
        "url": "https://github.com/supabase/cli/releases",
        "note": "Download from GitHub Releases"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Run `supabase login` to authenticate",
      "Set SUPABASE_ACCESS_TOKEN for CI/CD"
    ],
    "tags": [
      "database",
      "backend",
      "auth",
      "serverless"
    ],
    "examples": [
      "supabase projects list",
      "supabase db push",
      "supabase functions deploy my-function"
    ]
  },
  {
    "id": "terraform",
    "name": "terraform",
    "display_name": "Terraform CLI",
    "description": "Infrastructure as Code — provision and manage cloud resources declaratively",
    "command": "terraform",
    "homepage": "https://www.terraform.io",
    "aliases": [
      "tf"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "recommended_version": ">=1.7.0",
    "install_default": "brew",
    "install_default_package": "terraform",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://developer.hashicorp.com/terraform/install",
        "note": "Download from HashiCorp"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Configure provider credentials (AWS, GCP, Azure) before use",
      "Use HCP Terraform for remote state management"
    ],
    "tags": [
      "infrastructure",
      "iac",
      "cloud",
      "devops"
    ],
    "examples": [
      "terraform init",
      "terraform plan -out=plan.tfplan",
      "terraform apply plan.tfplan",
      "terraform state list"
    ]
  },
  {
    "id": "turso",
    "name": "turso",
    "display_name": "Turso CLI",
    "description": "CLI for Turso — the edge SQLite database built on libSQL",
    "command": "turso",
    "homepage": "https://turso.tech",
    "aliases": [],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "install_default": "brew",
    "install_default_package": "tursodatabase/tap/turso",
    "install_alternatives": [
      {
        "type": "binary",
        "url": "https://docs.turso.tech/cli/installation",
        "note": "Install via official script"
      }
    ],
    "prerequisites": [],
    "auth_notes": [
      "Run `turso auth login` to authenticate"
    ],
    "tags": [
      "database",
      "sqlite",
      "edge"
    ],
    "examples": [
      "turso db list",
      "turso db create my-db",
      "turso db shell my-db"
    ]
  },
  {
    "id": "vercel",
    "name": "vercel",
    "display_name": "Vercel CLI",
    "description": "Deploy and manage Vercel projects from the command line",
    "command": "vercel",
    "homepage": "https://vercel.com/docs/cli",
    "aliases": [
      "vc"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": true,
    "recommended_version": ">=37.0.0",
    "install_default": "npm",
    "install_default_package": "vercel",
    "install_alternatives": [],
    "prerequisites": [
      "node"
    ],
    "auth_notes": [
      "Run `vercel login` to authenticate",
      "Deployment requires a linked project or --yes for auto-setup"
    ],
    "tags": [
      "deploy",
      "hosting",
      "serverless",
      "frontend"
    ],
    "examples": [
      "vercel deploy",
      "vercel env ls",
      "vercel domains ls"
    ]
  },
  {
    "id": "wrangler",
    "name": "wrangler",
    "display_name": "Cloudflare Wrangler",
    "description": "CLI for Cloudflare Workers — develop, test, and deploy serverless functions",
    "command": "wrangler",
    "homepage": "https://developers.cloudflare.com/workers/wrangler",
    "aliases": [
      "wrangler"
    ],
    "platforms": [
      "macos",
      "linux",
      "windows"
    ],
    "agent_friendly": true,
    "supports_json": false,
    "recommended_version": ">=3.0.0",
    "install_default": "npm",
    "install_default_package": "wrangler",
    "install_alternatives": [],
    "prerequisites": [
      "node"
    ],
    "auth_notes": [
      "Run `wrangler login` to authenticate via browser",
      "Or set CLOUDFLARE_API_TOKEN environment variable"
    ],
    "tags": [
      "cloudflare",
      "deploy",
      "serverless",
      "workers",
      "edge"
    ],
    "examples": [
      "wrangler init my-project",
      "wrangler deploy",
      "wrangler dev"
    ]
  }
];

export const allTags: string[] = [
  "auth",
  "aws",
  "backend",
  "build",
  "cloud",
  "cloudflare",
  "collaboration",
  "containers",
  "database",
  "deploy",
  "devops",
  "docs",
  "drive",
  "edge",
  "feishu",
  "fintech",
  "frontend",
  "git",
  "github",
  "gmail",
  "google",
  "hosting",
  "iac",
  "infrastructure",
  "jamstack",
  "kubernetes",
  "lark",
  "messaging",
  "orchestration",
  "payments",
  "productivity",
  "scm",
  "serverless",
  "sheets",
  "sqlite",
  "stripe",
  "vcs",
  "webhooks",
  "workers",
  "workspace"
];
