// This file is generated by scripts/generate-tool-verification.mjs.
// Do not edit it by hand.

import type { ToolVerificationResult } from "./tool-verification";

export const toolVerificationResults: ToolVerificationResult[] = [
  {
    "tool_id": "vercel",
    "verified_at": "2026-04-04T06:36:46Z",
    "runner_os": "ubuntu-latest",
    "install_method": "npm",
    "install_status": "installed",
    "doctor_passed": true,
    "checks": {
      "help": {
        "status": "supported",
        "command": [
          "vercel",
          "--help"
        ],
        "evidence": "exit code 0"
      },
      "version": {
        "status": "supported",
        "command": [
          "vercel",
          "--version"
        ],
        "evidence": "exit code 0"
      },
      "json": {
        "status": "not_supported",
        "command": [
          "vercel",
          "--help"
        ],
        "evidence": "--json or --format json was not observed in help output"
      },
      "yes": {
        "status": "not_supported",
        "command": [
          "vercel",
          "--help"
        ],
        "evidence": "--yes was not observed in help output"
      },
      "dry_run": {
        "status": "not_supported",
        "command": [
          "vercel",
          "--help"
        ],
        "evidence": "--dry-run was not observed in help output"
      },
      "schema": {
        "status": "not_supported",
        "command": [
          "vercel",
          "schema",
          "--help"
        ],
        "evidence": "schema command exited with code 1"
      }
    }
  }
];
